apiVersion: "v1"
kind: "Pod"
metadata:
  annotations: {}
  labels:
  jenkins: "slave"
spec:
  containers:
  - name: node-12
    image: node:12.16.1-alpine3.9
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bitnami/kubectl:1.18.1
    tty: true
    command:
    - cat
securityContext:
runAsUser: 0
volumes:
- name: docker-sock
hostPath:
  path: /var/run/docker.sock